In [18]:
from systems import system_13
import numpy as np

diego2144 = np.array([628.33045,299.99307,299.99307,159.74125,159.74125,159.74125,159.74125,159.74125,159.74125,77.40922,77.40922,92.40855,86.00891])

diego24173 = np.array([628.08088,298.79312,298.79312,159.53795,159.53795,159.53795,159.53795,159.53795,159.53795,76.92247,76.92247,91.63009,91.63009])
pothya = np.array([628.32, 299.06,299.17,159.73,159.73,159.73,159.73,159.72,159.72, 75.47,77.33,92.10,90.59])
 
samedagh = np.array([617.1943, 300.4246,297.2810,165.63,159.0019,164.5568,140.7621,157.1320,165.9530,76.51676,74.81078,80.65879,120.0779])
  
system_13().costs(diego2144)

pothya.sum()

2520.3999999999996

In [7]:
system_13().pg_min

array([ 0,  0,  0, 60, 60, 60, 60, 60, 60, 40, 40, 55, 55])

In [8]:
system_13().pg_max

array([680, 360, 360, 180, 180, 180, 180, 180, 180, 120, 120, 120, 120])

In [9]:
system_13().a_k

array([0.00028, 0.00056, 0.00056, 0.00324, 0.00324, 0.00324, 0.00324,
       0.00324, 0.00324, 0.00284, 0.00284, 0.00284, 0.00284])

In [10]:
system_13().b_k

array([8.1 , 8.1 , 8.1 , 7.74, 7.74, 7.74, 7.74, 7.74, 7.74, 8.6 , 8.6 ,
       8.6 , 8.6 ])

In [12]:
system_13().c_k


array([550, 309, 307, 240, 240, 240, 240, 240, 240, 126, 126, 126, 126])

In [13]:
system_13().e_k

array([300, 200, 200, 150, 150, 150, 150, 150, 150, 100, 100, 100, 100])

In [14]:
system_13().f_k

array([0.035, 0.042, 0.042, 0.063, 0.063, 0.063, 0.063, 0.063, 0.063,
       0.084, 0.084, 0.084, 0.084])